"""empty message

Revision ID: 064726a9448a
Revises: 802971bcf39c
Create Date: 2023-02-02 19:09:40.321462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064726a9448a'
down_revision = '802971bcf39c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=250), nullable=False))
    op.add_column('user', sa.Column('last_ame', sa.String(length=250), nullable=False))
    op.drop_column('user', 'FirstName')
    op.drop_column('user', 'LastName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('LastName', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('FirstName', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_column('user', 'last_ame')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
