"""empty message

Revision ID: 51bb9af80406
Revises: f37ee131e76e
Create Date: 2023-02-02 18:18:39.559227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51bb9af80406'
down_revision = 'f37ee131e76e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach_review', sa.Column('review', sa.String(length=250), nullable=True))
    op.add_column('workout_review', sa.Column('review', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_review', 'review')
    op.drop_column('coach_review', 'review')
    # ### end Alembic commands ###
