"""empty message

Revision ID: 5483c9822a20
Revises: 86cfd302d4f6
Create Date: 2023-02-02 18:05:49.506956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5483c9822a20'
down_revision = '86cfd302d4f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('video', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coach.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise__status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise_assign.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('coach', sa.Column('facebook', sa.String(length=250), nullable=True))
    op.add_column('coach', sa.Column('twitter', sa.String(length=250), nullable=True))
    op.add_column('coach', sa.Column('instagram', sa.String(length=250), nullable=True))
    op.add_column('coach', sa.Column('tiktok', sa.String(length=250), nullable=True))
    op.drop_column('coach', 'socials')
    op.add_column('user', sa.Column('facebook', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('twitter', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('instagram', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('tiktok', sa.String(length=250), nullable=True))
    op.add_column('workout', sa.Column('exercise_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'exercise_count')
    op.drop_column('user', 'tiktok')
    op.drop_column('user', 'instagram')
    op.drop_column('user', 'twitter')
    op.drop_column('user', 'facebook')
    op.add_column('coach', sa.Column('socials', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('coach', 'tiktok')
    op.drop_column('coach', 'instagram')
    op.drop_column('coach', 'twitter')
    op.drop_column('coach', 'facebook')
    op.drop_table('exercise__status')
    op.drop_table('workout_categories')
    op.drop_table('exercise_library')
    # ### end Alembic commands ###
