"""empty message

Revision ID: a1e3fd608196
Revises: 5483c9822a20
Create Date: 2023-02-02 18:09:49.875378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e3fd608196'
down_revision = '5483c9822a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_assign', sa.Column('exercise_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exercise_assign', 'exercise_library', ['exercise_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise_assign', type_='foreignkey')
    op.drop_column('exercise_assign', 'exercise_id')
    # ### end Alembic commands ###
