"""empty message

Revision ID: f37ee131e76e
Revises: 62a8364d0d9c
Create Date: 2023-02-02 18:16:20.851571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f37ee131e76e'
down_revision = '62a8364d0d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_library', sa.Column('description', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_library', 'description')
    # ### end Alembic commands ###
